/* Generated by Yosys 0.53+98 (git sha1 50b63c648, g++ 13.3.0-6ubuntu2~24.04 -Og -fPIC) */

(* top =  1  *)
(* src = "test.v:1.1-5.10" *)
module top(in1, in2, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "test.v:1.25-1.28" *)
  input [1:0] in1;
  wire [1:0] in1;
  (* src = "test.v:1.42-1.45" *)
  input [1:0] in2;
  wire [1:0] in2;
  (* src = "test.v:1.60-1.63" *)
  output [3:0] out;
  wire [3:0] out;
  NOT _14_ (
    .A(in1[0]),
    .Y(_12_)
  );
  NOT _15_ (
    .A(in2[0]),
    .Y(_13_)
  );
  NAND _16_ (
    .A(in1[1]),
    .B(in2[1]),
    .Y(_00_)
  );
  NOT _17_ (
    .A(_00_),
    .Y(_01_)
  );
  NOR _18_ (
    .A(_12_),
    .B(_13_),
    .Y(_02_)
  );
  NAND _19_ (
    .A(in1[0]),
    .B(in2[0]),
    .Y(_03_)
  );
  NOR _20_ (
    .A(in1[1]),
    .B(in2[1]),
    .Y(_04_)
  );
  NOT _21_ (
    .A(_04_),
    .Y(_05_)
  );
  NOR _22_ (
    .A(_01_),
    .B(_04_),
    .Y(_06_)
  );
  NAND _23_ (
    .A(_00_),
    .B(_05_),
    .Y(_07_)
  );
  NOR _24_ (
    .A(_03_),
    .B(_07_),
    .Y(_08_)
  );
  NAND _25_ (
    .A(_02_),
    .B(_06_),
    .Y(_09_)
  );
  NAND _26_ (
    .A(_00_),
    .B(_09_),
    .Y(out[2])
  );
  NOR _27_ (
    .A(_02_),
    .B(_06_),
    .Y(_10_)
  );
  NOR _28_ (
    .A(_08_),
    .B(_10_),
    .Y(out[1])
  );
  NOR _29_ (
    .A(in1[0]),
    .B(in2[0]),
    .Y(_11_)
  );
  NOR _30_ (
    .A(_02_),
    .B(_11_),
    .Y(out[0])
  );
  assign out[3] = 1'h0;
endmodule
