#ifndef EQUIVFUSION_REPLICATE_TO_CONCAT_PASSES_H
#define EQUIVFUSION_REPLICATE_TO_CONCAT_PASSES_H

#include "mlir/Pass/Pass.h"

namespace circt {

#define GEN_PASS_DECL_EQUIVFUSIONREPLICATETOCONCAT
#define GEN_PASS_REGISTRATION
#include "circt-passes/ReplicateToConcat/Passes.h.inc"

}

#endif //EQUIVFUSION_REPLICATE_TO_CONCAT_PASSES_H