name: Build environment setup
description: Configure build env for EquivFusion
runs:
  using: composite
  steps:
    - name: Install Linux Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt install libreadline8 libreadline-dev
