name: Setup environment
description: Configure environment for EquivFusion
runs:
  using: composite
  steps:
    - name: Install Linux Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install libreadline8 libreadline-dev  # for build
        sudo apt-get install libz3-dev z3                  # for test

    - name: Linux runtime environment
      shell: bash
      run: |
        echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH
        echo "procs=$(nproc)" >> $GITHUB_ENV