name: Setup Test environment
description: Setup test environment for EquivFusion
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        pip install meson   # for install bitwuzla

