name: Setup Test environment
description: Setup test environment for EquivFusion
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        pip install meson   # for install bitwuzla

    - name: Install z3
      shell: bash
      run: |
        sudo apt update
        sudo apt install libz3-dev z3   # install z3
