name: Run Integration Tests
description: 'Runs integration tests'

runs:
  using: 'composite'
  steps:
    - name: Run Integration Tests
      shell: bash
      run: |
        echo "Run Integration Tests"
        python3 test/integration_tests/scripts/main.py

    - name: Upload Tests Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-tests-artifacts
        path: log